import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import type { PageProps } from '@/Types'
import { I18N, getStrings } from '@/Config'
import { Button } from '@root/components/ui/button'
import Link from 'next/link'
import { Header } from '@/Layouts'

import '@/styles/globals.css'
import '@/styles/globals.sass'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const generateStaticParams = async () => {
  return I18N.locales.map(locale => ({ lang: locale }))
}

type RootLayoutProps = PageProps & React.PropsWithChildren

const RootLayout: React.FC<RootLayoutProps> = async ({ children, params }) => {
  const strings = await getStrings(params.lang)

  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        {/* <Providers> */}

          <Header />

          <main>


            <p>
              {strings.app.title}
            </p>

            <Button asChild>
              <Link href={'/fr'}>
                FRANCAIS
              </Link>
            </Button>

            <Button asChild>
              <Link href={'/en'}>
                ENGLISH
              </Link>
            </Button>



            {children}
          </main>

          <footer>

          </footer>

        {/* </Providers> */}
      </body>
    </html>
  )
}

export default RootLayout
